#!/bin/bash

echo "user to delete:" 
read username

check=`cat /etc/passwd | grep $username`
if [ "$check" != "$NULL" ]; then
	if [ "$(pgrep -u $username)" != "$NULL" ]; then
		sudo kill -9 $(pgrep -u $username)
	fi
	sudo userdel -r $username
	echo "deletion complete"
else
	echo "User doesnt exist"
fi

