#!/bin/sh

echo "Enter commit message"
read message
git add .
git commit -m"${message}"
if [ -n "$(git status - porcelain)" ];
then
 echo "Already up to date"
else
 git status
 echo "Pushing"
 git push -u origin master
 echo "Job done, consider pushing more often"
fi
